# Generated by Django 3.2.5 on 2023-07-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('datetime', models.DateField()),
                ('location', models.TimeField(null=True)),
                ('description', models.TimeField(null=True)),
            ],
        ),
    ]
