# Generated by Django 3.2.5 on 2023-07-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_api', '0004_auto_20230718_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('phoneNumber', models.TextField()),
            ],
        ),
    ]
