# Generated by Django 3.2.5 on 2023-07-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_api', '0006_auto_20230719_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingListNumber',
        ),
    ]
