# Generated by Django 3.2.5 on 2023-07-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingListNumber',
            new_name='MessagingListNumber',
        ),
    ]
